<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ClaimsEngine.Api.Tests</RootNamespace>
    <Threshold>85</Threshold>
    <Include>[ClaimsEngine.Api]*,[ClaimsEngine.Infrastructure]*</Include>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClaimsEngine.Api\ClaimsEngine.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
