// <auto-generated />
using System;
using ClaimsEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaimsEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260918043227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimsEngine.Application.Ports.IdempotencyRecord", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Subject", "Key");

                    b.HasIndex("CreatedAt");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("ClaimsEngine.Domain.Claims.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedPayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ClaimedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("EligiblePayout")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("FiledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FiledAt");

                    b.HasIndex("PolicyId", "Status");

                    b.HasIndex("Status", "ReviewStartedAt");

                    b.ToTable("claims", null, t =>
                        {
                            t.HasCheckConstraint("ck_claims_claimed_amount_positive", "\"ClaimedAmount\" > 0");

                            t.HasCheckConstraint("ck_claims_eligible_payout_non_negative", "\"EligiblePayout\" >= 0");
                        });
                });

            modelBuilder.Entity("ClaimsEngine.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CoverageLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Deductible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("HolderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LifetimePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("policies", null, t =>
                        {
                            t.HasCheckConstraint("ck_policies_coverage_limit_positive", "\"CoverageLimit\" > 0");

                            t.HasCheckConstraint("ck_policies_deductible_below_limit", "\"Deductible\" >= 0 AND \"Deductible\" < \"CoverageLimit\"");

                            t.HasCheckConstraint("ck_policies_period", "\"EffectiveTo\" > \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("ClaimsEngine.Domain.Claims.Claim", b =>
                {
                    b.HasOne("ClaimsEngine.Domain.Policies.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("ClaimsEngine.Domain.Claims.ClaimHistoryEntry", "History", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<string>("ActorRole")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ClaimId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FromStatus")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Note")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("ClaimId", "At");

                            b1.ToTable("claim_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");
                        });

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
