#!/usr/bin/env bash
# Generates docs/TEST-CATALOG.md from the test sources: one row per test method.
#   Test      = Class.Method (the name is the scenario; tests are named after the case they cover)
#   Covers    = the <summary> of the test class (the rule or area the class exercises)
#   Codes     = error codes asserted in the method body (snake_case string literals)
#   Kind      = Fact / Theory / PostgresFact (PostgreSQL only)
# Run it after adding tests; CONTRIBUTING.md asks for the regenerated file in the pull request.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/TEST-CATALOG.md"
mkdir -p "$ROOT/docs"

{
  echo "# Test catalog"
  echo
  echo "Generated by \`scripts/generate-test-catalog.sh\` from the test sources (do not edit by hand)."
  echo "Each row is one test method. The method name states the scenario; the class summary states the rule"
  echo "or area under test; the codes column lists the error codes the test asserts."
  echo
  find "$ROOT/tests" -name '*.cs' -not -path '*/Support/*' -not -path '*/bin/*' -not -path '*/obj/*' | sort | while read -r file; do
    project=$(basename "$(dirname "$file")")
    [[ "$project" == ClaimsEngine.* ]] || project=$(basename "$(dirname "$(dirname "$file")")")
    awk -v project="$project" '
      function humanize(name,    s) {
        s = name
        gsub(/_/, " / ", s)
        s = gensub(/([a-z0-9])([A-Z])/, "\\1 \\2", "g", s)
        s = gensub(/([A-Z])([A-Z][a-z])/, "\\1 \\2", "g", s)
        return s
      }
      function flush(    codes, c, list) {
        if (method == "") return
        list = ""
        for (c in seen) list = list (list == "" ? "" : ", ") "`" c "`"
        printf("| %s | `%s.%s` | %s | %s | %s |\n", kind, cls, method, humanize(method), summary, (list == "" ? "-" : list))
        method = ""; delete seen
      }
      /\/\/\/ <summary>/ { pending = $0; sub(/.*<summary>/, "", pending); sub(/<\/summary>.*/, "", pending); gsub(/\|/, "\\|", pending); next }
      /^(public|internal) (sealed |abstract )?class / { flush(); cls = $0; sub(/.*class /, "", cls); sub(/[ (<].*/, "", cls); summary = pending; pending = ""; next }
      /^    \[(Fact|Theory|PostgresFact)/ { flush(); kind = $0; sub(/^    \[/, "", kind); sub(/[\]( ].*/, "", kind); if (kind == "PostgresFact") kind = "PostgresFact (PostgreSQL only)"; capture = 1; next }
      capture && /^    public .*\(/ { method = $0; sub(/\(.*/, "", method); sub(/.* /, "", method); capture = 0; next }
      method != "" {
        line = $0
        while (match(line, /"[a-z]+(_[a-z]+)+"/)) {
          code = substr(line, RSTART + 1, RLENGTH - 2)
          if (code !~ /^(yyyy|http)/) seen[code] = 1
          line = substr(line, RSTART + RLENGTH)
        }
      }
      END { flush() }
    ' "$file" | sed "s/^/| $project /"
  done | awk '
    BEGIN { prev = "" }
    {
      proj = $0; sub(/^\| /, "", proj); sub(/ \|.*/, "", proj)
      if (proj != prev) {
        if (prev != "") print ""
        printf("## %s\n\n| Project | Kind | Test | Scenario | Covers (class summary) | Codes asserted |\n|---|---|---|---|---|---|\n", proj)
        prev = proj
      }
      print
    }'
  echo
  echo "Counts: $(grep -c '^| ClaimsEngine' "$OUT" 2>/dev/null || echo 0) rows at last generation (see the test run summary in the README for executed test cases; theories expand into several cases)."
} > "$OUT.tmp"

rows=$(grep -c '^| ClaimsEngine' "$OUT.tmp")
sed -i "s/^Counts: .*/Counts: $rows test methods across the three test projects (theories expand into several executed cases each)./" "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "Wrote $OUT ($rows test methods)"
