<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ClaimsEngine.Api</RootNamespace>
    <AssemblyName>ClaimsEngine.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaimsEngine.Application\ClaimsEngine.Application.csproj" />
    <ProjectReference Include="..\ClaimsEngine.Infrastructure\ClaimsEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="prometheus-net.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClaimsEngine.Api.Tests" />
  </ItemGroup>

</Project>
